#!/bin/sh

### BEGIN INIT INFO
# Provides:          otgether
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Setup usb ethernet gadget mode
### END INIT INFO

. /etc/init.d/functions

start() {
	printf "Starting usb ethernet gadget mode: "
	modprobe dwc2
	ifup usb0
	echo "OK"
}

stop() {
	printf "Stopping usb ethernet gadget mode: "
	ifdown usb0
	rmmod dwc2
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
esac